############# English navigation ##############


[[main]]
name = "Blog"
url = "blog/"
weight = 2

[[main]]
name = "About"
url = "about/"
weight = 3

# main menu
[[main]]
name = "Contact"
url = "contact/"
weight = 4
