############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Posts"
url = "blog/"
weight = 3

[[main]]
name = "Quotes"
url = "quotes/"
weight = 4

[[main]]
name = "Contact"
url = "contact/"
weight = 5

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Posts"
url = "blog/"
weight = 2

[[footer]]
name = "About"
url = "about/"
weight = 3

[[footer]]
name = "Contact"
url = "contact/"
weight = 4


